"""Update Interview model: profile_id added, null allowed, relations to question added

Revision ID: 637f4283803b
Revises: a2ab5aa3aa37
Create Date: 2025-05-19 15:17:23.607154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '637f4283803b'
down_revision: Union[str, None] = 'a2ab5aa3aa37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('profile_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'interviews', 'user_profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_column('interviews', 'profile_id')
    # ### end Alembic commands ###
