"""Modify Interview model, fields from user_profile described explicitly

Revision ID: b8d1e74bc49b
Revises: 5af71447527b
Create Date: 2025-05-14 16:10:32.032513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d1e74bc49b'
down_revision: Union[str, None] = '5af71447527b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('job_position', sa.String(), nullable=False))
    op.add_column('interviews', sa.Column('experience', sa.Float(), nullable=False))
    op.add_column('interviews', sa.Column('tech_stack', sa.String(), nullable=False))
    op.drop_constraint('interviews_user_profile_id_fkey', 'interviews', type_='foreignkey')
    op.drop_column('interviews', 'user_profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('user_profile_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('interviews_user_profile_id_fkey', 'interviews', 'user_profiles', ['user_profile_id'], ['id'])
    op.drop_column('interviews', 'tech_stack')
    op.drop_column('interviews', 'experience')
    op.drop_column('interviews', 'job_position')
    # ### end Alembic commands ###
