"""Upgrade interview (is_active, feedback)

Revision ID: 5bbd182107f0
Revises: 96d9f07d70ba
Create Date: 2025-05-26 16:15:39.550517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bbd182107f0'
down_revision: Union[str, None] = '96d9f07d70ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE interviews SET is_active = FALSE")
    op.alter_column('interviews', 'is_active', nullable=False)
    op.add_column('interviews', sa.Column('feedback', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'feedback')
    op.drop_column('interviews', 'is_active')
    # ### end Alembic commands ###
