"""Update Interview

Revision ID: 573e911f0a89
Revises: 93bf5345843e
Create Date: 2025-05-25 13:41:54.441348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573e911f0a89'
down_revision: Union[str, None] = '93bf5345843e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('interviews_profile_id_fkey', 'interviews', type_='foreignkey')
    op.drop_column('interviews', 'profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('interviews_profile_id_fkey', 'interviews', 'user_profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###
